# 1. K?t n?i t?i PostgreSQL (Nh? check port 5432)
#spring.datasource.url=jdbc:postgresql://localhost:5432/financedb
#spring.datasource.username=postgres
#spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. C?u hình Hibernate (T? ??ng t?o b?ng)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. M? c?ng Console (N?u mu?n soi l?i)
spring.jpa.open-in-view=false

#4. Không l?u cache c?
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

cloudinary.cloud-name=dlzlg8fty
cloudinary.api-key=676549645229826
cloudinary.api-secret=TTX7PF5JczSZieph1jO_o7ICPLc

# Google OAuth2
google.client-id=538574294548-29k7g54irvt65p4mmtu6pc4qcf1tqqap.apps.googleusercontent.com

# ===============================
# C?U HÌNH G?I EMAIL (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Thay b?ng ??a ch? Gmail c?a homie
spring.mail.username=hoanghaile175@gmail.com
# Thay b?ng cái M?t kh?u ?ng d?ng 16 ch? cái v?a copy (Vi?t li?n không kho?ng tr?ng)
spring.mail.password=otqwegkwdsmiyhwe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# -------------------------------
# C?U HÌNH GIAO DI?N SWAGGER
# -------------------------------
# 1. B?t Swagger s?p x?p các Nhóm (Tag) theo b?ng ch? cái (1, 2, 3, 4...)
springdoc.swagger-ui.tags-sorter=alpha

# 2. S?p x?p các API bên trong m?i nhóm theo lo?i (DELETE -> GET -> POST -> PUT) cho g?n gàng
springdoc.swagger-ui.operations-sorter=method

# Ép ki?u tr? v? c?a LocalDateTime/LocalDate sang chu?n ISO 8601
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss'Z'
spring.jackson.time-zone=UTC

# Dùng bi?n môi tr??ng cho database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Hibernate t? t?o b?ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# C?u hình Port ??ng cho Render
server.port=${PORT:8080}