
#spring.datasource.url=jdbc:postgresql://localhost:5432/financedb
#spring.datasource.username=postgres
#spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.open-in-view=false


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

cloudinary.cloud-name=dlzlg8fty
cloudinary.api-key=676549645229826
cloudinary.api-secret=TTX7PF5JczSZieph1jO_o7ICPLc

# Google OAuth2
google.client-id=538574294548-29k7g54irvt65p4mmtu6pc4qcf1tqqap.apps.googleusercontent.com


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=hoanghaile175@gmail.com

spring.mail.password=otqwegkwdsmiyhwe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


springdoc.swagger-ui.tags-sorter=alpha


springdoc.swagger-ui.operations-sorter=method


spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss'Z'
spring.jackson.time-zone=UTC

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}